version: "3.0"
services:
    database:
        image: mongo
    client:
        build: client
        image: dixit_client
        volumes:
            - "./client:/client"
        ports:
            - '0.0.0.0:80:8080'
        depends_on:
            - server
    server:
        build: server
        image: dixit_server
        volumes:
            - "./server:/server"
        depends_on:
            - database
#    proxy:
#        image: nginx
#        volumes:
#            - "./proxy.conf:/etc/nginx/conf.d/default.conf"
#        ports:
#            - "80:80"
#        depends_on:
#            - client
#            - server
